name: Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları al
      uses: actions/checkout@v3

    - name: Docker Hub'a login ol
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Docker image build et
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ayseactions:tagname .

    - name: Docker image push et
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ayseactions:tagname

    - name: Sunucuya bağlan ve container'ı güncelle
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/ayseactions:tagname
          docker stop ayseactions || true
          docker rm ayseactions || true
          docker run -d --name ayseactions -p 80:80 ${{ secrets.DOCKER_USERNAME }}/ayseactions:tagname
