name: Build, Push & Deploy

on:
  push:
    branches:
      - main  # main branch'e push yapıldığında tetiklenir

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları al
      uses: actions/checkout@v3  # Repo'nun kodlarını al

    - name: Docker Hub'a login ol
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  # Docker Hub'a login

    - name: Docker image build et
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ayseactions:latest .  # Docker imajını build et

    - name: Docker image push et
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ayseactions:latest  # Docker imajını Docker Hub'a push et

    - name: Railway'e deploy et
      run: |
        # Railway CLI'yi kur
        curl -fsSL https://railway.app/deploy | sh  
        
        # Railway'e bağlantı sağla
        railway link

        # Docker Hub'dan imajı al ve çalıştır
        railway run "docker run -d -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/ayseactions:latest"
      env:
        RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}  # Railway API key'ini environment variable olarak ekle
